# Generated by Django 6.0.1 on 2026-01-13 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220114_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielinks',
            options={'verbose_name': 'Movie Link'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year_of_producation',
            new_name='year_of_production',
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], max_length=2),
        ),
    ]
