# Generated by Django 6.0.1 on 2026-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_profile_favorites_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', to='movie.movie'),
        ),
    ]
