# Generated by Django 6.0.1 on 2026-01-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_actor_alter_movie_created_movie_new_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
    ]
