# Generated by Django 6.0.1 on 2026-01-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_remove_movie_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='new_cast',
            new_name='cast',
        ),
    ]
