# Generated by Django 6.0.1 on 2026-01-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
    ]
