# Generated by Django 6.0.1 on 2026-01-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_remove_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genres',
            new_name='category',
        ),
    ]
